# Copyright (c) Intel Corporation
# Copyright (c) 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cache:
  directories:
  - $HOME/.m2
sudo: false
language:
    - java
jdk:
    - oraclejdk8
git:
  depth: 99999
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
    true
addons:
  sonarcloud:
    organization: "opensecuritycontroller-org"
    token:
      secure: "A0NHOHWHvpQPiRptXkQQ3Je3zoOS3zeO5ZHpfjRm1AauGg4rFH4omzqvLkmij2nRmZipOefSkRmJS7Gs6m2o9tMjM+K+zEv19iw8/3NgxmQPO+E7RgAACkfzR1LZFELirVZyHsq9JFShXeZrspINEGlTvMfCt+BhVD471mNxd+dJxmjdAlPGPgNtDQ646KhPGDN0bhZT+UpmHr15VhUYxsl6q3LYEEMBl33b2OS71xjovZj61S7VA7YTHMKcyDTZ6RzwZefokoumpdT/2nnpJK9zeV95uRWDdzTI5iN+1OJh1iLXWNpyw9VsPliY4hvor07LJsMFTuC/95r0l0K5PAlq6GZojCWdYni1TN7KXiNDWPQ4rxPywwcMDesUB5Gc63CZr81aV5hOj8HUy8f8+8FRQkK8qhX6cDwTc1OvcCyz5skVFfN7jqOgQzF5qC05hWwC6ilElPRUegcWvIPlJeWRPZH27yd2jda2PnhxYVnDQpXIHhR/wSjFE9gEjtfMcM8bgDfOeoBaCaO+1uPn0ow6toehWVZcShZlSaI2ZJ+efBEBgTPFwn+QhNmlbBk1Hu3wcvQ8z8MeSR7fZH5CP1gwD3oZEUn808bqK01LAlM29HVlhcuPYlZFa8rc8h7m9fdMirO+Q5IiudJR5XRp4PW7JKSkqK+BGmifniSpntI="
script:
# the following command line builds the project, executes the SonarCloud analysis
    - if [[ -n "${TRAVIS_PULL_REQUEST_SLUG}" || "$(cut -d'/' -f1 <<<${TRAVIS_REPO_SLUG})" != opensecuritycontroller ]]; then
        echo "Skipping sonar analysis as this is a pull request or a build of a fork";
        mvn install;
      else
        mvn install sonar:sonar;
      fi